# Generated by Django 3.0.3 on 2020-02-24 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=30)),
                ('DOB', models.DateField()),
                ('Email', models.CharField(default=None, max_length=20)),
                ('Phone', models.CharField(max_length=12)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Prefer not to disclose')], max_length=1)),
            ],
            options={
                'db_table': 'Admin',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('C_Id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(default=None, max_length=30)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(default=None, max_length=30)),
                ('DOB', models.DateField(blank=True)),
                ('Email', models.CharField(default=None, max_length=20)),
                ('Phone', models.CharField(max_length=12)),
                ('Gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Prefer not to disclose')], max_length=1)),
            ],
            options={
                'db_table': 'customer',
            },
        ),
        migrations.CreateModel(
            name='sub_category',
            fields=[
                ('S_Id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Name', models.CharField(default=None, max_length=30)),
                ('C_Id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='foodmaza.Category', verbose_name='Category')),
            ],
            options={
                'db_table': 'sub_category',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('Item_id', models.IntegerField(editable=False, primary_key=True, serialize=False)),
                ('Item_name', models.CharField(default=None, max_length=30)),
                ('Item_image', models.ImageField(upload_to='images/')),
                ('Discription', models.CharField(default=None, max_length=100)),
                ('S_Id', models.ForeignKey(default=None, on_delete=django.db.models.deletion.SET_DEFAULT, to='foodmaza.sub_category', verbose_name='sub_category')),
            ],
            options={
                'db_table': 'Item',
            },
        ),
    ]
