# Generated by Django 3.0.3 on 2020-03-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmaza', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admin',
            name='Password',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='customer',
            name='Password',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
