# Generated by Django 3.0.3 on 2020-03-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodmaza', '0002_auto_20200302_1507'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='Item_price',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
